" TODO: learn vim script
" TODO: compile vim with clipboard feature
" TODO: function to group html related abbreviations/maps
" TODO: function to toggle group of options

let mapleader=" "
let g:netrw_banner=0
colorscheme cs

" recursively search directories and subdirectories
set path+=**
set incsearch
"set number rnu
set termguicolors bg=dark
set tabstop=4 softtabstop=4 shiftwidth=4
set cindent
set expandtab
"set smartindent autoindent
"set makeprg=gcc\ -o\ main\ %\ -lm
set makeprg=gcc\ -o\ main\ %\ -Wall\ -Werror
set noruler noshowmode showcmd
set scrolloff=2
set tw=80
set laststatus=0
"set nohlsearch
"set guicursor=""
"set statusline=""
"set foldmethod=indent
"set foldlevel=1
"set foldclose=all
"set undofile
"set undodir=~/.cache/vim/undo
"set undolevels=1000 "set undoreload=3000

syntax enable
filetype plugin on

autocmd FileType html,css setlocal tabstop=2 softtabstop=2 shiftwidth=2 

nnoremap <leader><cr> :w<cr>:so ~/.config/vim/vimrc<cr>
nnoremap <leader>v :e ~/.dotfiles/.config/vim/vimrc<cr>

nnoremap <leader>w :w<cr>
nnoremap <leader><c-w> :wq<cr>
nnoremap <leader>q :q!<cr>

nnoremap <leader>Y mmggVG:w ! xclip -sel clip<cr><cr>`mzz
vnoremap <leader>y :w ! xclip -sel clip<cr><cr>
vnoremap <leader>p "_dP

nnoremap <silent><c-k> :bn<cr>`"
nnoremap <silent><c-j> :bp<cr>`"
nnoremap <leader>d :bd<cr>
nnoremap <leader>j :ls<cr>:b 
nnoremap <leader>k :e <c-d>
nnoremap <leader>g :vimgrep   %<left><left><left>

nnoremap <leader><c-p> :copen 6<cr>
nnoremap <silent><c-l> :cnext<cr>
nnoremap <silent><c-h> :cprev<cr>
nnoremap <leader>m :w<cr>:!clear<cr>:make<cr>
nnoremap <leader>e :w<cr>:make<cr>:!clear;./main<cr>

nnoremap [<leader> mmo<esc>0D`m
nnoremap ]<leader> mmO<esc>0D`m

nnoremap ' `
nnoremap '' ``
nnoremap ` '
nnoremap `` ''
nnoremap <silent> { :execute "keepjumps norm! " . v:count1 . "{"<cr>
nnoremap <silent> } :execute "keepjumps norm! " . v:count1 . "}"<cr>

nnoremap <c-d> <c-d>zz
nnoremap <c-u> <c-u>zz
nnoremap <c-f> <c-f>zz
nnoremap <c-b> <c-b>zz
nnoremap G GGzz
nnoremap g; g;zz
nnoremap g, g,zz
nnoremap p p=G
nnoremap P P=gg<c-o>zz

" TODO: make a function to group html related abbreviations/maps
"ia html <esc>:-1r ~/dotfiles/.config/vim/.index.html<cr>/body<cr>o

" REMINDERS:
" q: - enter command line editing in normal mode
" gd - go to declaration of local variable under the cursor
" gi
" gg=G fix indentation of whole file
"
" use w, W, b, B, e, E, ge, gE
"
" # - find next occurence of word under cursor backwards
" * - find next occurence of word under cursor forward
"
" Move cursor relative to visible area of window
" H - high
" M - mid
" L - low
"
" position the screen with the cursor at:
" zt - top
" zb - bottom
"
" gq - wrap line
" gggqG - wrap all lines in the file longer than set textwidth into multiple lines
" vim script functions
"let s:hidden_all = 0
"function! ToggleHiddenAll()
"    if s:hidden_all  == 0
"        let s:hidden_all = 1
"        set noshowmode
"        set noruler
"        set laststatus=0
"        set noshowcmd
"    else
"        let s:hidden_all = 0
"        set showmode
"        set ruler
"        set laststatus=2
"        set showcmd
"    endif
"endfunction
"
"nnoremap <S-h> :call ToggleHiddenAll()<cr>
