[window]
decorations = "None"

[font]
size = 18.0
normal.family = "IosevkaSS14"
italic.family = "IosevkaSS14"
bold.family = "IosevkaSS14"
bold_italic.family = "IosevkaSS14"
#normal.family = "Roboto Mono"
#italic.family = "Roboto Mono"
#bold.family = "Roboto Mono"
#bold_italic.family = "Roboto Mono"

[colors]
#cursor = { text = "#000000", cursor = "#ffffff" }
#cursor = { text = "#000000", cursor = "#ffee32" }
vi_mode_cursor = { text = "#000000", cursor = "#4FFF5E" }
#primary.background = "#040404"
primary.background = "#07070b"

[keyboard]
bindings = [
{key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{key = "J", mods = "Control|Shift", action = "ScrollHalfPageDown" },
{key = "K", mods = "Control|Shift", action = "ScrollHalfPageUp" }
]
